INSERT INTO LDestado (Estado,Pais) VALUES ('Acre','Brasil')    
INSERT INTO LDestado (Estado,Pais) VALUES ('Alagoas','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Amapá','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Amazonas','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Bahia','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Ceará','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Distrito Federal','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Espírito Santo','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Goiás','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Maranhão','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Mato Grosso','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Mato Grosso do Sul','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Minas Gerais','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Pará','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Paraíba','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Paraná','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Pernambuco','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Piauí','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Rio de Janeiro','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Rio Grande do Sul','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Rio Grando do Norte','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Rondonia','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Roraima','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Santa Catarina','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('São Paulo','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Sergipe','Brasil') 
INSERT INTO LDestado (Estado,Pais) VALUES ('Tocantins','Brasil') 