INSERT INTO LDEstado (Estado,Pais) VALUES ('Alabama','Estados Unidos')   
INSERT INTO LDEstado (Estado,Pais) VALUES ('Alasca','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Arizona','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Arkansas','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Califórnia','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Carolina do Norte','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Carolina do Sul','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Colorado','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Connecticut','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Dakota do Norte','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Dakota do Sul','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Delaware','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Distrito de Colúmbia','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Flórida','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Geórgia','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Havaí','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Idaho','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Illinois','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Indiana','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Iowa','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Kansas','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Kentucky','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Louisiana','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Maine','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Maryland','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Massachusetts','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Michigan','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Minnesota','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Mississippi','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Missouri','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Montana','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Nebraska','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Nevada','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('New Hampshire','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Nova Jersey','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Nova York','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Novo México','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Ohio','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Oklahoma','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Oregon','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Pensilvânia','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Rhode Island','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Tennessee','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Texas','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Utah','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Vermont','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Virgínia','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Virgínia Ocidental','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Washington','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Wisconsin','Estados Unidos') 
INSERT INTO LDEstado (Estado,Pais) VALUES ('Wyoming','Estados Unidos') 