INSERT INTO LDpais VALUES ('Afeganistão')
INSERT INTO LDpais VALUES ('Albânia') 
INSERT INTO LDpais VALUES ('Afeganistão') 
INSERT INTO LDpais VALUES ('Albânia') 
INSERT INTO LDpais VALUES ('Alemanha') 
INSERT INTO LDpais VALUES ('Andorra') 
INSERT INTO LDpais VALUES ('Angola') 
INSERT INTO LDpais VALUES ('Anguilla') 
INSERT INTO LDpais VALUES ('Antilhas Holandesas') 
INSERT INTO LDpais VALUES ('Antártida') 
INSERT INTO LDpais VALUES ('Antígua e Barbuda') 
INSERT INTO LDpais VALUES ('Argentina') 
INSERT INTO LDpais VALUES ('Argélia') 
INSERT INTO LDpais VALUES ('Armênia') 
INSERT INTO LDpais VALUES ('Aruba') 
INSERT INTO LDpais VALUES ('Arábia Saudita') 
INSERT INTO LDpais VALUES ('Austrália') 
INSERT INTO LDpais VALUES ('Azerbaijão') 
INSERT INTO LDpais VALUES ('Bahamas') 
INSERT INTO LDpais VALUES ('Bahrein') 
INSERT INTO LDpais VALUES ('Bangladesh') 
INSERT INTO LDpais VALUES ('Barbados') 
INSERT INTO LDpais VALUES ('Belarus') 
INSERT INTO LDpais VALUES ('Belize') 
INSERT INTO LDpais VALUES ('Benin') 
INSERT INTO LDpais VALUES ('Bermuda') 
INSERT INTO LDpais VALUES ('Bolívia') 
INSERT INTO LDpais VALUES ('Botsuana') 
INSERT INTO LDpais VALUES ('Brasil') 
INSERT INTO LDpais VALUES ('Brunei') 
INSERT INTO LDpais VALUES ('Bulgária') 
INSERT INTO LDpais VALUES ('Burkina Faso') 
INSERT INTO LDpais VALUES ('Burundi') 
INSERT INTO LDpais VALUES ('Butão') 
INSERT INTO LDpais VALUES ('Bélgica') 
INSERT INTO LDpais VALUES ('Bósnia e Herzegovina') 
INSERT INTO LDpais VALUES ('Cabo Verde') 
INSERT INTO LDpais VALUES ('Camarões') 
INSERT INTO LDpais VALUES ('Camboja') 
INSERT INTO LDpais VALUES ('Canadá') 
INSERT INTO LDpais VALUES ('Catar') 
INSERT INTO LDpais VALUES ('Cazaquistão') 
INSERT INTO LDpais VALUES ('Chade') 
INSERT INTO LDpais VALUES ('Chile') 
INSERT INTO LDpais VALUES ('China') 
INSERT INTO LDpais VALUES ('Chipre') 
INSERT INTO LDpais VALUES ('Cidade do Vaticano (Santa Sé)') 
INSERT INTO LDpais VALUES ('Cingapura') 
INSERT INTO LDpais VALUES ('Colômbia') 
INSERT INTO LDpais VALUES ('Comores') 
INSERT INTO LDpais VALUES ('Congo') 
INSERT INTO LDpais VALUES ('Congo, República Popular do') 
INSERT INTO LDpais VALUES ('Coréia') 
INSERT INTO LDpais VALUES ('Coréia do Norte') 
INSERT INTO LDpais VALUES ('Costa Rica') 
INSERT INTO LDpais VALUES ('Costa do Marfim') 
INSERT INTO LDpais VALUES ('Croácia (Hrvatska)') 
INSERT INTO LDpais VALUES ('Cuba') 
INSERT INTO LDpais VALUES ('Dinamarca') 
INSERT INTO LDpais VALUES ('Djibuti') 
INSERT INTO LDpais VALUES ('Dominica') 
INSERT INTO LDpais VALUES ('Egito') 
INSERT INTO LDpais VALUES ('El Salvador') 
INSERT INTO LDpais VALUES ('Emirados Árabes Unidos') 
INSERT INTO LDpais VALUES ('Equador') 
INSERT INTO LDpais VALUES ('Eritréia') 
INSERT INTO LDpais VALUES ('Eslováquia') 
INSERT INTO LDpais VALUES ('Eslovênia') 
INSERT INTO LDpais VALUES ('Espanha') 
INSERT INTO LDpais VALUES ('Estados Unidos') 
INSERT INTO LDpais VALUES ('Estônia') 
INSERT INTO LDpais VALUES ('Etiópia') 
INSERT INTO LDpais VALUES ('Fiji') 
INSERT INTO LDpais VALUES ('Filipinas') 
INSERT INTO LDpais VALUES ('Finlândia') 
INSERT INTO LDpais VALUES ('França') 
INSERT INTO LDpais VALUES ('Gabão') 
INSERT INTO LDpais VALUES ('Gana') 
INSERT INTO LDpais VALUES ('Geórgia') 
INSERT INTO LDpais VALUES ('Gibraltar') 
INSERT INTO LDpais VALUES ('Grenada') 
INSERT INTO LDpais VALUES ('Groenlândia') 
INSERT INTO LDpais VALUES ('Grécia') 
INSERT INTO LDpais VALUES ('Guadalupe') 
INSERT INTO LDpais VALUES ('Guam') 
INSERT INTO LDpais VALUES ('Guatemala') 
INSERT INTO LDpais VALUES ('Guiana') 
INSERT INTO LDpais VALUES ('Guiana Francesa') 
INSERT INTO LDpais VALUES ('Guiné') 
INSERT INTO LDpais VALUES ('Guiné Equatorial') 
INSERT INTO LDpais VALUES ('Guiné-Bissau') 
INSERT INTO LDpais VALUES ('Gâmbia') 
INSERT INTO LDpais VALUES ('Haiti') 
INSERT INTO LDpais VALUES ('Holanda') 
INSERT INTO LDpais VALUES ('Honduras') 
INSERT INTO LDpais VALUES ('Hong Kong RAE, República Popular da China') 
INSERT INTO LDpais VALUES ('Hungria') 
INSERT INTO LDpais VALUES ('Ilha Bouvet') 
INSERT INTO LDpais VALUES ('Ilha Norfolk') 
INSERT INTO LDpais VALUES ('Ilhas Cayman') 
INSERT INTO LDpais VALUES ('Ilhas Christmas') 
INSERT INTO LDpais VALUES ('Ilhas Cocos (Keeling)') 
INSERT INTO LDpais VALUES ('Ilhas Cook') 
INSERT INTO LDpais VALUES ('Ilhas Faroés') 
INSERT INTO LDpais VALUES ('Ilhas Geórgia do Sul e Sandwich do Sul') 
INSERT INTO LDpais VALUES ('Ilhas Heard e McDonald') 
INSERT INTO LDpais VALUES ('Ilhas Malvinas') 
INSERT INTO LDpais VALUES ('Ilhas Marianas do Norte') 
INSERT INTO LDpais VALUES ('Ilhas Marshall') 
INSERT INTO LDpais VALUES ('Ilhas Salomão') 
INSERT INTO LDpais VALUES ('Ilhas Svalbard e Jan Mayen') 
INSERT INTO LDpais VALUES ('Ilhas Turks e Caicos') 
INSERT INTO LDpais VALUES ('Ilhas Virgens Americanas') 
INSERT INTO LDpais VALUES ('Ilhas Virgens Britânicas') 
INSERT INTO LDpais VALUES ('Ilhas Wallis e Futuna') 
INSERT INTO LDpais VALUES ('Indonésia') 
INSERT INTO LDpais VALUES ('Iraque') 
INSERT INTO LDpais VALUES ('Irlanda') 
INSERT INTO LDpais VALUES ('Irã') 
INSERT INTO LDpais VALUES ('Islândia') 
INSERT INTO LDpais VALUES ('Israel') 
INSERT INTO LDpais VALUES ('Itália') 
INSERT INTO LDpais VALUES ('Iugoslávia') 
INSERT INTO LDpais VALUES ('Iêmen') 
INSERT INTO LDpais VALUES ('Jamaica') 
INSERT INTO LDpais VALUES ('Japão') 
INSERT INTO LDpais VALUES ('Jordânia') 
INSERT INTO LDpais VALUES ('Kiribati') 
INSERT INTO LDpais VALUES ('Kuwait') 
INSERT INTO LDpais VALUES ('Laos') 
INSERT INTO LDpais VALUES ('Lesoto') 
INSERT INTO LDpais VALUES ('Letônia') 
INSERT INTO LDpais VALUES ('Libéria') 
INSERT INTO LDpais VALUES ('Liechtenstein') 
INSERT INTO LDpais VALUES ('Lituânia') 
INSERT INTO LDpais VALUES ('Luxemburgo') 
INSERT INTO LDpais VALUES ('Líbano') 
INSERT INTO LDpais VALUES ('Líbia') 
INSERT INTO LDpais VALUES ('Macau') 
INSERT INTO LDpais VALUES ('Macedônia') 
INSERT INTO LDpais VALUES ('Madagascar') 
INSERT INTO LDpais VALUES ('Malaui') 
INSERT INTO LDpais VALUES ('Maldivas') 
INSERT INTO LDpais VALUES ('Mali') 
INSERT INTO LDpais VALUES ('Malta') 
INSERT INTO LDpais VALUES ('Malásia') 
INSERT INTO LDpais VALUES ('Marrocos') 
INSERT INTO LDpais VALUES ('Martinica') 
INSERT INTO LDpais VALUES ('Mauritânia') 
INSERT INTO LDpais VALUES ('Maurício') 
INSERT INTO LDpais VALUES ('Mayotte') 
INSERT INTO LDpais VALUES ('Micronésia') 
INSERT INTO LDpais VALUES ('Moldávia') 
INSERT INTO LDpais VALUES ('Mongólia') 
INSERT INTO LDpais VALUES ('Montserrat') 
INSERT INTO LDpais VALUES ('Moçambique') 
INSERT INTO LDpais VALUES ('Myanma') 
INSERT INTO LDpais VALUES ('México') 
INSERT INTO LDpais VALUES ('Mônaco') 
INSERT INTO LDpais VALUES ('Namíbia') 
INSERT INTO LDpais VALUES ('Nauru') 
INSERT INTO LDpais VALUES ('Nepal') 
INSERT INTO LDpais VALUES ('Nicarágua') 
INSERT INTO LDpais VALUES ('Nigéria') 
INSERT INTO LDpais VALUES ('Niue') 
INSERT INTO LDpais VALUES ('Noruega') 
INSERT INTO LDpais VALUES ('Nova Caledônia') 
INSERT INTO LDpais VALUES ('Nova Zelândia') 
INSERT INTO LDpais VALUES ('Níger') 
INSERT INTO LDpais VALUES ('Omã') 
INSERT INTO LDpais VALUES ('Palau') 
INSERT INTO LDpais VALUES ('Panamá') 
INSERT INTO LDpais VALUES ('Papua-Nova Guiné') 
INSERT INTO LDpais VALUES ('Paquistão') 
INSERT INTO LDpais VALUES ('Paraguai') 
INSERT INTO LDpais VALUES ('Peru') 
INSERT INTO LDpais VALUES ('Pitcairn') 
INSERT INTO LDpais VALUES ('Polinésia Francesa') 
INSERT INTO LDpais VALUES ('Polônia') 
INSERT INTO LDpais VALUES ('Porto Rico') 
INSERT INTO LDpais VALUES ('Portugal') 
INSERT INTO LDpais VALUES ('Quirguistão') 
INSERT INTO LDpais VALUES ('Quênia') 
INSERT INTO LDpais VALUES ('Reino Unido') 
INSERT INTO LDpais VALUES ('República Centro-Africana') 
INSERT INTO LDpais VALUES ('República Dominicana') 
INSERT INTO LDpais VALUES ('República Tcheca') 
INSERT INTO LDpais VALUES ('Reunião') 
INSERT INTO LDpais VALUES ('Romênia') 
INSERT INTO LDpais VALUES ('Ruanda') 
INSERT INTO LDpais VALUES ('Rússia') 
INSERT INTO LDpais VALUES ('Saint Kitts e Névis') 
INSERT INTO LDpais VALUES ('Samoa') 
INSERT INTO LDpais VALUES ('Samoa Americana') 
INSERT INTO LDpais VALUES ('San Marino') 
INSERT INTO LDpais VALUES ('Santa Helena') 
INSERT INTO LDpais VALUES ('Santa Lúcia') 
INSERT INTO LDpais VALUES ('Senegal') 
INSERT INTO LDpais VALUES ('Serra Leoa') 
INSERT INTO LDpais VALUES ('Seychelles') 
INSERT INTO LDpais VALUES ('Somália') 
INSERT INTO LDpais VALUES ('Sri Lanka') 
INSERT INTO LDpais VALUES ('St. Pierre e Miquelon') 
INSERT INTO LDpais VALUES ('Suazilândia') 
INSERT INTO LDpais VALUES ('Sudão') 
INSERT INTO LDpais VALUES ('Suriname') 
INSERT INTO LDpais VALUES ('Suécia') 
INSERT INTO LDpais VALUES ('Suíça') 
INSERT INTO LDpais VALUES ('São Tomé e Príncipe') 
INSERT INTO LDpais VALUES ('São Vicente e Granadinas') 
INSERT INTO LDpais VALUES ('Síria') 
INSERT INTO LDpais VALUES ('Tadjiquistão') 
INSERT INTO LDpais VALUES ('Tailândia') 
INSERT INTO LDpais VALUES ('Taiwan') 
INSERT INTO LDpais VALUES ('Tanzânia') 
INSERT INTO LDpais VALUES ('Território Britânico do Oceano Índico') 
INSERT INTO LDpais VALUES ('Territórios Franceses do Sul') 
INSERT INTO LDpais VALUES ('Territórios Insulares dos EUA') 
INSERT INTO LDpais VALUES ('Timor Oriental') 
INSERT INTO LDpais VALUES ('Togo') 
INSERT INTO LDpais VALUES ('Tokelau') 
INSERT INTO LDpais VALUES ('Tonga') 
INSERT INTO LDpais VALUES ('Trinidad e Tobago') 
INSERT INTO LDpais VALUES ('Tunísia') 
INSERT INTO LDpais VALUES ('Turcomenistão') 
INSERT INTO LDpais VALUES ('Turquia') 
INSERT INTO LDpais VALUES ('Tuvalu') 
INSERT INTO LDpais VALUES ('Ucrânia') 
INSERT INTO LDpais VALUES ('Uganda') 
INSERT INTO LDpais VALUES ('Uruguai') 
INSERT INTO LDpais VALUES ('Uzbequistão') 
INSERT INTO LDpais VALUES ('Vanuatu') 
INSERT INTO LDpais VALUES ('Venezuela') 
INSERT INTO LDpais VALUES ('Vietnã') 
INSERT INTO LDpais VALUES ('Zimbábue') 
INSERT INTO LDpais VALUES ('Zâmbia') 
INSERT INTO LDpais VALUES ('África do Sul') 
INSERT INTO LDpais VALUES ('Áustria') 
INSERT INTO LDpais VALUES ('Índia') 