INSERT INTO LDresponsabilidade VALUES ('Autor principal')  
INSERT INTO LDresponsabilidade VALUES ('Cartógrafo') 
INSERT INTO LDresponsabilidade VALUES ('Co-orientador') 
INSERT INTO LDresponsabilidade VALUES ('Colaborador') 
INSERT INTO LDresponsabilidade VALUES ('Compilador') 
INSERT INTO LDresponsabilidade VALUES ('Coordenador') 
INSERT INTO LDresponsabilidade VALUES ('Diretor') 
INSERT INTO LDresponsabilidade VALUES ('Elenco') 
INSERT INTO LDresponsabilidade VALUES ('Entidade') 
INSERT INTO LDresponsabilidade VALUES ('Evento') 
INSERT INTO LDresponsabilidade VALUES ('Fotográfo') 
INSERT INTO LDresponsabilidade VALUES ('Ilustrador') 
INSERT INTO LDresponsabilidade VALUES ('Interprete') 
INSERT INTO LDresponsabilidade VALUES ('Montagem') 
INSERT INTO LDresponsabilidade VALUES ('Música') 
INSERT INTO LDresponsabilidade VALUES ('Organizador ') 
INSERT INTO LDresponsabilidade VALUES ('Orientador') 
INSERT INTO LDresponsabilidade VALUES ('Outros secundários') 
INSERT INTO LDresponsabilidade VALUES ('Revisor ') 
INSERT INTO LDresponsabilidade VALUES ('Roteirista') 
INSERT INTO LDresponsabilidade VALUES ('Tradutor') 